name: Clean up releases # So we don't overuse our quota

on: 
  workflow_run:
    workflows: ["Build and Release"]
    types: [completed]

jobs:
  delete_old_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 3 # keep the most recent 3 releases; make this 0 to delete all, or 1 to keep recent
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          